<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <Configurations>Developer - Debug;Release - Alpha;Release - Beta;Release - Final</Configurations>
    <Platforms>x64</Platforms>
    <TargetFramework>net48</TargetFramework>
    <AssemblyTitle>RimeWidgetBlueprintEditorPlugin</AssemblyTitle>
    <Product>RimeWidgetBlueprintEditorPlugin</Product>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <LangVersion>11</LangVersion>
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=$(MSBuildProjectName)\</PathMap>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Developer - Debug|x64' ">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Developer\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Alpha|x64' ">
    <OutputPath>bin\Release\Alpha\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Beta|x64'">
    <OutputPath>bin\Release\Beta\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Final|x64'">
    <OutputPath>bin\Release\Final\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
    <Reference Include="SharpDX.Direct3D11">
      <HintPath>..\..\FrostyEditor\ThirdParty\SharpDX.Direct3D11.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SharpDX.DXGI">
      <HintPath>..\..\FrostyEditor\ThirdParty\SharpDX.DXGI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FrostyControls\FrostyControls.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\FrostyHash\FrostyHash.vcxproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\FrostyPlugin\FrostyCore.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\FrostySdk\FrostySdk.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\LocalizedStringPlugin\LocalizedStringPlugin.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\TexturePlugin\TexturePlugin.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\Grid.png" />
    <None Remove="Images\Precise_OFF.png" />
    <None Remove="Images\Precise_ON.png" />
    <None Remove="Images\Refresh.png" />
    <None Remove="Images\UITypeIcon.png" />
    <Resource Include="Images\Grid.png" />
    <Resource Include="Images\Precise_OFF.png" />
    <Resource Include="Images\Precise_ON.png" />
    <Resource Include="Images\Refresh.png" />
    <Resource Include="Images\UITypeIcon.png" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command='xcopy /Y "$(TargetPath)" "$(SolutionDir)$(OutDir)Plugins\"' />
  </Target>

  <PropertyGroup>
    <EmitLegacyAssetsFileItems>True</EmitLegacyAssetsFileItems>
  </PropertyGroup>

</Project>
